app/portfolio/ecapp/urls.py
from django.urls import path
from . import views


app_name = 'ecapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('fav_products/', views.fav_products, name='fav_products'),
    path('my_products/', views.my_products, name='my_products'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('product/', views.detail_from_article, name='detail_from_article'),
    path('wheather_fav_new/', views.WheatherFavNew.as_view(),
         name='wheather_fav_new'),
    path('toggle_fav/', views.ToggleFav.as_view(), name='toggle_fav'),
    path('cart/<int:which_cart>/', views.cart, name='cart'),
    path('change_item_amount/<int:which_cart>/', views.change_item_amount,
         name='change_item_amount'),
    path('delete_cart_product/<int:which_cart>/<int:product_id>/',
         views.delete_cart_product, name='delete_cart_product'),
    path('order_history/', views.order_history, name='order_history'),
    path('sell/', views.sell, name='sell'),
    path('delete/<int:product_id>', views.delete, name='delete'),
]

app/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from ecapp import views as ec_views
from snsapp import views as sns_views


router = routers.DefaultRouter()
router.register('products', ec_views.ProductViewSet)
router.register('articles', sns_views.ArticleViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('ecapp/', include('ecapp.urls')),
    path('snsapp/', include('snsapp.urls')),
    path('api/', include(router.urls)),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/portfolio/snsapp/urls.py
from django.urls import path
from . import views

app_name = 'snsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('good_articles/', views.good_articles, name='good_articles'),
    path('my_articles/', views.my_articles, name='my_articles'),
    path('post_article/', views.post_article, name='post_article'),
    path('delete/<int:article_id>/', views.delete, name='delete'),
    path('change_good/', views.ChangeGood.as_view(), name='change_good'),
    path('gooded_articles/', views.GoodedArticles.as_view(), name='gooded_articles'),
]

app/portfolio/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import EmailAuthenticationForm

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('my_page/', views.my_page, name='my_page'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('friend_list/', views.friend_list, name='friend_list'),
    path('add_friend/<int:user_id>', views.add_friend, name='add_friend'),
    path('point_history/', views.point_history, name='point_history'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
]

app/portfolio/snsapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ecapp.models import Product


class Article(models.Model):
    """投稿記事"""
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    content = models.TextField(max_length=300)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, blank=True, null=True)
    evaluation = models.PositiveIntegerField(blank=True, null=True)
    good_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)


class Good(models.Model):
    """いいねカウント"""
    pusher = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

app/portfolio/snsapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from ecapp.models import Sale


class ArticleForm(forms.Form):
    content = forms.CharField(
        max_length=500,
        widget=forms.Textarea(
            attrs={'placeholder': '商品の評価を投稿する場合は商品を選択してください'})
    )
    evaluation = forms.IntegerField(required=False)

    def __init__(self, user_id, *args, **kwargs):
        '''自身が購入した商品をproductフィールドの選択肢として設置'''
        super(ArticleForm, self).__init__(*args, **kwargs)
        user_model = get_user_model()
        user = user_model.objects.get(id=user_id)
        sales = Sale.objects.filter(user=user)
        products = []
        for sale in sales:
            product = sale.product
            if product not in products:
                products.append(product)
        self.fields['product'] = forms.ChoiceField(
            choices=[(None, '-')] + [(product.pk, product.name)
                                     for product in products],
            required=False
        )

        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

app/portfolio/snsapp/views.py
import re
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.http import JsonResponse
from rest_framework import viewsets
from rest_framework import permissions, authentication
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from .models import Article, Good
from .forms import ArticleForm
from users.models import Friend, PointFluctuation
from users.forms import SearchForm
from ecapp.models import Product
from .serializers import ArticleSerializer


def index(request):
    '''get:snsトップページを表示　post:検索結果で絞り込んでsnsトップページを表示'''
    search_form = SearchForm(request.POST or None)
    articles = Article.objects.all().order_by('-created_at')
    # 検索フォーム
    if request.method == 'POST':
        if search_form.is_valid():
            user = request.user
            select = search_form.cleaned_data['select']
            keyword = search_form.cleaned_data['keyword']

            # ユーザー選択時の処理
            if select == '友人のみ':
                result_users = []
                if user.is_authenticated:
                    for friend_instance in Friend.objects.filter(owner=user):
                        friend = friend_instance.friends
                        result_users.append(friend)
            if select == '全体':
                user_model = get_user_model()
                result_users = user_model.objects.all()

            searched_articles = []
            for result_user in result_users:
                articles = Article.objects.filter(author=result_user)
                for article in articles:
                    searched_articles.append(article)

            # ワード検索時の処理
            if keyword:
                articles = []
                for article in searched_articles:
                    author = article.author.name
                    content = article.content
                    product = article.product
                    if product:
                        product = product.name
                    else:
                        product = ''
                    text_list = [author, content, product]
                    text = ' '.join(text_list)
                    if re.findall(keyword, text, re.IGNORECASE):
                        articles.append(article)
                messages.success(request, f'"{keyword}"の検索結果（{select}）')
            if not keyword:
                articles = searched_articles
                messages.success(request, f'絞り込み（{select}）')
        else:
            messages.warning(request, '無効な検索です')
            return redirect('snsapp:index')

    num = request.GET.get('page')
    if not num:
        num = 1
    articles = Paginator(articles, 20)
    articles = articles.get_page(num)
    context = {
        'search_form': search_form,
        'articles': articles,
        'next': 'sns',
    }
    return render(request, 'snsapp/index.html', context)


@login_required
def good_articles(request):
    '''いいねした記事で絞り込んでsnsトップページを表示'''
    user = request.user
    good_objects = Good.objects.filter(pusher=user).order_by('-created_at')
    articles = []
    for good in good_objects:
        article = good.article
        articles.append(article)
    num = request.GET.get('page')
    articles = Paginator(articles, 20)
    articles = articles.get_page(num)
    return render(request, 'snsapp/index.html', {'articles': articles})


@login_required
def my_articles(request):
    '''自身の記事で絞り込んでsnsトップページを表示'''
    user = request.user
    articles = Article.objects.filter(author=user).order_by('-created_at')
    num = request.GET.get('page')
    articles = Paginator(articles, 20)
    articles = articles.get_page(num)
    return render(request, 'snsapp/index.html', {'articles': articles})


@login_required
def post_article(request):
    '''get:記事投稿ページを表示　post:記事投稿処理'''
    if request.method == 'POST':
        author = request.user
        content = request.POST['content']
        product_id = request.POST['product']
        if product_id:
            product = Product.objects.get(pk=product_id)
            evaluation = request.POST['evaluation']
            article = Article.objects.create(
                author=author, content=content, product=product, evaluation=evaluation)
        else:
            article = Article.objects.create(author=author, content=content)
        article.save()
        messages.success(request, '記事を投稿しました')
        return redirect('snsapp:index')
    else:
        user_id = request.user.id
        article_form = ArticleForm(user_id=user_id)
    return render(request, 'snsapp/post_article.html', {'article_form': article_form})


@login_required
@require_POST
def delete(request, article_id):
    '''自身の記事を削除し、元のページを表示'''
    article = Article.objects.get(id=article_id)
    article.delete()
    if 'top' in request.POST:
        return redirect('users:index')
    elif 'user' in request.POST:
        user_id = request.user.id
        return redirect('users:user_detail', user_id=user_id)
    elif 'product' in request.POST:
        product_id = request.POST.get('product_id')
        return redirect('ecapp:detail', product_id=product_id)
    elif 'sns' in request.POST:
        return redirect('snsapp:index')


class GoodedArticles(APIView):
    '''いいねした記事のIDを返す'''

    def get(self, request):
        article_ids = []
        if request.user.is_authenticated:
            good_instances = Good.objects.filter(pusher=request.user)
            for good_instance in good_instances:
                gooded_article = good_instance.article
                article_ids.append(gooded_article.id)
            # 削除されている投稿を取り除く
            for i, article_id in enumerate(article_ids):
                if not Article.objects.filter(id=article_id):
                    article_ids.pop(i)
        data = {
            'article_ids': article_ids,
        }
        return JsonResponse(data, safe=False)


class ChangeGood(APIView):
    '''記事のいいね状態を切り替える'''
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        user = request.user
        pk = request.GET.get('pk')
        article = get_object_or_404(Article, pk=pk)
        good = Good.objects.filter(pusher=user).filter(article=article)
        # 既にgoodを押していた場合
        if good:
            article.good_count -= 1
            article.save()
            PointFluctuation.objects.create(
                user=article.author, event=f'記事"{article.content}"のgoodが外されました', change=-1
            )
            good.delete()
        # 新しくgoodを押した場合
        else:
            article.good_count += 1
            article.save()
            PointFluctuation.objects.create(
                user=article.author, event=f'記事"{article.content}"にgoodが押されました', change=1
            )
            Good.objects.create(
                pusher=user, article=article
            )
        return Response(None)


class ArticleViewSet(viewsets.ModelViewSet):
    """API endpoint"""
    queryset = Article.objects.all().order_by('-created_at')
    serializer_class = ArticleSerializer
    permission_classes = [permissions.IsAuthenticated]

app/portfolio/templates/snsapp/article_list.html
{% if not articles %}
<h5 class="text-center font-weight-bold text-muted mb-4 mt-1">未投稿</h5>
{% else %}
{% for article in articles %}
<div class="media row mb-3 border-bottom border-info p-3 shadow-sm">
    <div class="col-3 text-center">
        <a class="d-inline-block mx-auto"
            href="{% url 'ecapp:detail_from_article' %}?product_id={{ article.product.id }}&article_id={{ article.id }}">
            <img class="img-sm" src="{{ article.product.image.url }}" alt="" class="product-img">
        </a>
    </div>
    <div class="media-body col-9">
        {% if article.product %}
        <a class="media-headig h4"
            href="{% url 'ecapp:detail_from_article' %}?product_id={{ article.product.id }}&article_id={{ article.id }}">
            {{ article.product.name }}
        </a>
        {% else %}
        <a class="media-headig h6" href="#">
            [ 一般コメント ]
        </a>
        {% endif %}

        {% if article.author == request.user %}
        <form action="{% url 'snsapp:delete' article.id %}" method="post" class="d-inline ml-3">
            {% csrf_token %}
            <input class="btn btn-outline-danger" type="submit" next="{{ next }}"
                onclick="return confirm('本当に削除しますか？');" value="削除">
        </form>
        {% endif %}
        {% if article.evaluation %}
        <ul style="list-style: none;" class="pl-0">
            <li class="d-inline-block">
                <star-icon :eval="eval" data-id="1" data-eval="{{ article.evaluation }}"></star-icon>
                <star-icon :eval="eval" data-id="2" data-eval="{{ article.evaluation }}"></star-icon>
                <star-icon :eval="eval" data-id="3" data-eval="{{ article.evaluation }}"></star-icon>
                <star-icon :eval="eval" data-id="4" data-eval="{{ article.evaluation }}"></star-icon>
                <star-icon :eval="eval" data-id="5" data-eval="{{ article.evaluation }}"></star-icon>
            </li>
        </ul>
        {% endif %}
        <p>{{ article.content }}</p>
        <div class="mt-auto float-right">
            <div class="d-flex align-items-end">
                <span class="font-italic mr-2">{{ article.created_at | date:"Y/m/d f" }}</span>
                by<a href="{% url 'users:user_detail' article.author.id %}">{{ article.author.name }}</a>
            </div>
        </div>
    </div>
    <article-good id="good" ref="{{ article.id }}" data-id="{{ article.id }}" data-count="{{ article.good_count }}"
        data-authenticated="{{ request.user.is_authenticated }}">
    </article-good>
</div>
{% endfor %}
{% endif %}

app/portfolio/templates/snsapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if 'my_articles' in request.path %}
<div class="alert alert-info">
    <h3>自身の記事</h3>
</div>

{% elif 'good_articles' in request.path %}
<div class="alert alert-info">
    <h3>goodした記事</h3>
</div>

{% else %}
<div class="alert alert-info">
    <h3>SNS TOP</h3>
</div>
<form action="{% url 'snsapp:index' %}" method="POST" class="search mx-auto row">{% csrf_token %}
    <div class="input-group col-lg-4 col-md-6 row ml-auto mr-4 mb-4">
        <div class="col-3 p-0">
            {{ search_form.select }}
        </div>
        <div class="col-8 p-0">
            {{ search_form.keyword }}
        </div>
        <div class="input-group-append col-1 p-0">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</form>
{% endif %}

<div class="container-fulid px-3 mb-5">
    <div class="container bg-info rounded-lg">
        <p class="h2 text-light d-inline-block ml-3 my-1">最近の投稿</p>
    </div>
    <div class="container pt-3 mb-5 border border-info rounded" id="article">
        {% include 'snsapp/article_list.html' %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if articles.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'snsapp:index' %}?page=1">&laquo;</a></li>
                <li class="page-item">
                    <a class="page-link" href="{% url 'snsapp:index' %}?page={{ articles.previous_page_number }}">
                        {{ articles.previous_page_number }}</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <span class="page-link" href="#">{{ articles.number }}</span>
                </li>
                {% if articles.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'snsapp:index' %}?page={{ articles.next_page_number }}">
                        {{ articles.next_page_number }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{% url 'snsapp:index' %}?page={{ articles.paginator.num_pages }}">
                        &raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript" src="https://kit.fontawesome.com/c25d00f6dc.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'js/display_eval.js' %}"></script>
<script type="text/javascript" src="{% static 'js/article.js' %}"></script>
{% endblock %}

app/portfolio/templates/snsapp/post_article.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="alert alert-info">
    <h3>記事を投稿</h3>
</div>

<div class="container">
    <form action="{% url 'snsapp:post_article' %}" method="post">{% csrf_token %}
        <label class="mt-3">記事内容</label>
        {{ article_form.content }}
        <label class="mt-3">商品</label><span class="text-muted small ml-2">※自身が購入した商品のみ選択可能です</span>
        {{ article_form.product }}
        <label class="mt-3">商品の評価</label>
        <div id="stars" class="">
            <input type="hidden" name="evaluation" :value="[[ eval ]]" class="form-control">
            <ul style="list-style: none;">
                <li class="d-inline-block border">
                    <star-icon :eval="eval" @change-eval="eval=$event" data-id="1"></star-icon>
                    <star-icon :eval="eval" @change-eval="eval=$event" data-id="2"></star-icon>
                    <star-icon :eval="eval" @change-eval="eval=$event" data-id="3"></star-icon>
                    <star-icon :eval="eval" @change-eval="eval=$event" data-id="4"></star-icon>
                    <star-icon :eval="eval" @change-eval="eval=$event" data-id="5"></star-icon>
                </li>
            </ul>
        </div>
        <div class="form-group text-center">
            <button class="btn btn-primary mt-3" type="submit">投稿</button>
        </div>
    </form>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript" src="https://kit.fontawesome.com/c25d00f6dc.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/vue"></script>
<script type="text/javascript" src="{% static 'js/post_eval.js' %}"></script>
{% endblock %}