app/portfolio/ecapp/urls.py
from django.urls import path
from . import views


app_name = 'ecapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('fav_products/', views.fav_products, name='fav_products'),
    path('my_products/', views.my_products, name='my_products'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('product/', views.detail_from_article, name='detail_from_article'),
    path('wheather_fav_new/', views.WheatherFavNew.as_view(),
         name='wheather_fav_new'),
    path('toggle_fav/', views.ToggleFav.as_view(), name='toggle_fav'),
    path('cart/<int:which_cart>/', views.cart, name='cart'),
    path('change_item_amount/<int:which_cart>/', views.change_item_amount,
         name='change_item_amount'),
    path('delete_cart_product/<int:which_cart>/<int:product_id>/',
         views.delete_cart_product, name='delete_cart_product'),
    path('order_history/', views.order_history, name='order_history'),
    path('sell/', views.sell, name='sell'),
    path('delete/<int:product_id>', views.delete, name='delete'),
]

app/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from ecapp import views as ec_views
from snsapp import views as sns_views


router = routers.DefaultRouter()
router.register('products', ec_views.ProductViewSet)
router.register('articles', sns_views.ArticleViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('ecapp/', include('ecapp.urls')),
    path('snsapp/', include('snsapp.urls')),
    path('api/', include(router.urls)),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/portfolio/snsapp/urls.py
from django.urls import path
from . import views

app_name = 'snsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('good_articles/', views.good_articles, name='good_articles'),
    path('my_articles/', views.my_articles, name='my_articles'),
    path('post_article/', views.post_article, name='post_article'),
    path('delete/<int:article_id>/', views.delete, name='delete'),
    path('change_good/', views.ChangeGood.as_view(), name='change_good'),
    path('gooded_articles/', views.GoodedArticles.as_view(), name='gooded_articles'),
]

app/portfolio/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import EmailAuthenticationForm

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('my_page/', views.my_page, name='my_page'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('friend_list/', views.friend_list, name='friend_list'),
    path('add_friend/<int:user_id>', views.add_friend, name='add_friend'),
    path('point_history/', views.point_history, name='point_history'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
]

app/portfolio/templates/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Various Function Application</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block style %}{% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <a class="navbar-brand" href="{% url 'users:index' %}">Various Function Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">SNS</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'snsapp:index' %}" class="dropdown-item">TOP</a>
                        <a href="{% url 'snsapp:good_articles' %}" class="dropdown-item">goodした記事</a>
                        <a href="{% url 'snsapp:post_article' %}" class="dropdown-item">投稿</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">EC</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'ecapp:index' %}" class="dropdown-item">TOP</a>
                        <a href="{% url 'ecapp:fav_products' %}" class="dropdown-item">お気に入り</a>
                        <a href="{% url 'ecapp:cart' 0 %}" class="dropdown-item">カート</a>
                        <a href="{% url 'ecapp:order_history' %}" class="dropdown-item">注文履歴</a>
                        <a href="{% url 'ecapp:sell' %}" class="dropdown-item">出品</a>
                    </div>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">アカウント</a>
                    <div class="dropdown-menu">
                        {% if request.user.icon %}
                        <img class="dropdown-item rounded-circle img-md mx-auto px-1" src="{{ request.user.icon.url }}"
                            alt="">
                        {% else %}
                        <img class="dropdown-item rounded-circle img-md mx-auto px-1"
                            src="{% static 'default_icon.jpg' %}" alt="">
                        {% endif %}
                        <p class="dropdown-item disabled m-0">{{ request.user.name }}</p>
                        <p class="dropdown-item disabled m-0">Point: {{ request.user.point | intcomma }}</p>
                        <a class="dropdown-item" href="{% url 'users:my_page' %}">My Page</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'users:logout' %}"
                            onclick="return confirm('カート内の商品は全てリセットされます。本当にログアウトしますか？');">ログアウト</a>
                    </div>
                </li>
                {% endif %}
            </ul>
            {% if not request.user.is_authenticated %}
            <span>
                <a class="btn btn-outline-primary mx-20" href="{% url 'users:login' %}">ログイン</a>
                <a class="btn btn-outline-primary mx-20" href="{% url 'users:signup' %}">新規登録</a>
            </span>
            {% endif %}
        </div>
    </nav>

    <div class="container-fluid">
        {% for message in messages %}
        <p class="alert alert-{{ message.tags }} text-center">{{ message }}</p>
        {% endfor %}
        {% block content %}{% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    {% block script %}{% endblock %}
</body>

</html>