app/portfolio/ecapp/urls.py
from django.urls import path
from . import views


app_name = 'ecapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('fav_products/', views.fav_products, name='fav_products'),
    path('my_products/', views.my_products, name='my_products'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('product/', views.detail_from_article, name='detail_from_article'),
    path('wheather_fav_new/', views.WheatherFavNew.as_view(),
         name='wheather_fav_new'),
    path('toggle_fav/', views.ToggleFav.as_view(), name='toggle_fav'),
    path('cart/<int:which_cart>/', views.cart, name='cart'),
    path('change_item_amount/<int:which_cart>/', views.change_item_amount,
         name='change_item_amount'),
    path('delete_cart_product/<int:which_cart>/<int:product_id>/',
         views.delete_cart_product, name='delete_cart_product'),
    path('order_history/', views.order_history, name='order_history'),
    path('sell/', views.sell, name='sell'),
    path('delete/<int:product_id>', views.delete, name='delete'),
]

app/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from ecapp import views as ec_views
from snsapp import views as sns_views


router = routers.DefaultRouter()
router.register('products', ec_views.ProductViewSet)
router.register('articles', sns_views.ArticleViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('ecapp/', include('ecapp.urls')),
    path('snsapp/', include('snsapp.urls')),
    path('api/', include(router.urls)),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/portfolio/snsapp/urls.py
from django.urls import path
from . import views

app_name = 'snsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('good_articles/', views.good_articles, name='good_articles'),
    path('my_articles/', views.my_articles, name='my_articles'),
    path('post_article/', views.post_article, name='post_article'),
    path('delete/<int:article_id>/', views.delete, name='delete'),
    path('change_good/', views.ChangeGood.as_view(), name='change_good'),
    path('gooded_articles/', views.GoodedArticles.as_view(), name='gooded_articles'),
]

app/portfolio/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import EmailAuthenticationForm

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('my_page/', views.my_page, name='my_page'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('friend_list/', views.friend_list, name='friend_list'),
    path('add_friend/<int:user_id>', views.add_friend, name='add_friend'),
    path('point_history/', views.point_history, name='point_history'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
]

app/portfolio/ecapp/models.py
from django.db import models


class Product(models.Model):
    """商品"""
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=1)
    image = models.ImageField(upload_to='product')
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Sale(models.Model):
    """売上情報"""
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    amount = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField("商品単価")
    created_at = models.DateTimeField(auto_now_add=True)

app/portfolio/snsapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ecapp.models import Product


class Article(models.Model):
    """投稿記事"""
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    content = models.TextField(max_length=300)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, blank=True, null=True)
    evaluation = models.PositiveIntegerField(blank=True, null=True)
    good_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)


class Good(models.Model):
    """いいねカウント"""
    pusher = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

app/portfolio/users/views.py
import json
import requests
import datetime
from django.conf import settings
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from .models import Friend, PointFluctuation, Questionnaire
from snsapp.models import Article
from ecapp.models import Product
from .forms import CustomUserCreationForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm, QuestionnaireForm, ProfileForm


def index(request):
    '''トップページを表示'''
    products = Product.objects.all().order_by('-id')
    products = products[:20]
    articles = Article.objects.all().order_by('-created_at')
    article_num = request.GET.get('articles')
    if not article_num:
        article_num = 0
    article_num = int(article_num)
    if article_num == len(articles) and article_num != 0:
        messages.warning(request, '既に全ての記事を表示しています')
    else:
        article_num += 10
        articles = articles[:article_num]
        article_num = len(articles)
    context = {
        'products': products,
        'articles': articles,
        'article_num': article_num,
        'next': 'top',
    }
    return render(request, 'users/index.html', context)


@login_required
def my_page(request):
    '''マイページを表示'''
    return render(request, 'users/my_page.html')


@login_required
def edit_profile(request):
    '''get:プロフィール編集ページを表示　post:プロフィール編集処理'''
    user = request.user
    # プロフィールが更新されたとき
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            user.name = profile_form.cleaned_data['name']
            user.email = profile_form.cleaned_data['email']
            user.message = profile_form.cleaned_data['message']
            user.icon = profile_form.cleaned_data['icon']
            # 住所検索されたとき
            if 'search_address' in request.POST:
                zip_code = request.POST['zip_code']
                address = get_address(zip_code)
                profile_form = ProfileForm(
                    initial={'name': user.name, 'email': user.email, 'zip_code': zip_code, 'address': address})
                if not address:
                    messages.warning(request, "住所を取得できませんでした")
                    return redirect('users:edit_profile')
                return render(request, 'users/edit_profile.html', {'profile_form': profile_form})
            user.address = profile_form.cleaned_data['address']
            user.save()
            return redirect('users:my_page')
        else:
            messages.warning(request, '必須項目が入力されていません')
            return render(request, 'users/edit_profile.html', {'profile_form': profile_form})
    profile_form = ProfileForm(
        initial={'name': user.name, 'email': user.email, 'address': user.address, 'message': user.message, 'icon': user.icon})
    return render(request, 'users/edit_profile.html', {'profile_form': profile_form})


def user_detail(request, user_id):
    '''ユーザー詳細ページを表示'''
    user_model = get_user_model()
    user = user_model.objects.get(id=user_id)
    products = Product.objects.filter(owner=user).order_by('-created_at')
    articles = Article.objects.filter(author=user).order_by('-created_at')
    article_num = request.GET.get('articles')
    if not article_num:
        article_num = 0
    article_num = int(article_num)
    if article_num == len(articles) and article_num != 0:
        messages.warning(request, '既に全ての記事を表示しています')
    else:
        article_num += 10
        articles = articles[:article_num]
        article_num = len(articles)
    if Friend.objects.filter(owner=request.user).filter(friends=user):
        is_friend = True
    else:
        is_friend = False
    context = {
        'user': user,
        'products': products,
        'articles': articles,
        'is_friend': is_friend,
        'article_num': article_num,
        'next': 'user',
    }
    return render(request, 'users/user_detail.html', context)


@login_required
def friend_list(request):
    '''フレンドリストを表示'''
    user = request.user
    friend_instances = Friend.objects.filter(
        owner=user).order_by('-created_at')
    friends = []
    for friend_instance in friend_instances:
        friend = friend_instance.friends
        friends.append(friend)
    num = request.GET.get('page')
    friends = Paginator(friends, 10)
    friends = friends.get_page(num)
    return render(request, 'users/friend_list.html', {'friends': friends})


@login_required
def add_friend(request, user_id):
    '''ユーザーの友達状態を切り替える'''
    user = request.user
    user_model = get_user_model()
    friend = user_model.objects.get(id=user_id)
    friend_object = Friend.objects.filter(owner=user).filter(friends=friend)
    if friend_object:
        friend_object.delete()
    else:
        Friend.objects.create(owner=user, friends=friend)
    return redirect('users:user_detail', user_id=user_id)


@login_required
def point_history(request):
    '''ポイント履歴を表示'''
    user = request.user
    point_fluctuations = PointFluctuation.objects.filter(
        user=user).order_by('-created_at')
    num = request.GET.get('page')
    point_fluctuations = Paginator(point_fluctuations, 10)
    point_fluctuations = point_fluctuations.get_page(num)
    return render(request, 'users/point_history.html', {'point_fluctuations': point_fluctuations})


@login_required
def questionnaire(request):
    '''get:アンケートページを表示　post:アンケート回答処理'''
    user = request.user
    # アンケート回答済みのユーザーはリダイレクト
    questionnaire = Questionnaire.objects.filter(user=user)
    if questionnaire:
        messages.warning(request, 'アンケートに回答済みです')
        return redirect('users:my_page')

    questionnaire_form = QuestionnaireForm(request.POST or None)
    if questionnaire_form.is_valid():
        content = questionnaire_form.cleaned_data['content']
        evaluation = questionnaire_form.cleaned_data['evaluation']
        # ポイント付与
        user.point += 300
        user.save()
        PointFluctuation.objects.create(
            user=user, event='アンケートに回答', change=300)

        questionnaire = Questionnaire(
            user=user, content=content, evaluation=evaluation)
        questionnaire.save()
        # 開発者にメール送信
        subject = 'アンケート結果'
        message = f'評価　：　{evaluation}\n\n{content}'
        developer = get_user_model().objects.get(id=1)
        from_email = settings.DEFAULT_FROM_EMAIL
        developer.email_user(
            subject=subject, message=message, from_email=from_email)
        messages.success(request, 'アンケートにご協力いただきありがとうございます。300ポイントが付与されました。')
        return redirect('users:index')
    else:
        messages.warning(request, '必須項目が入力されていません')
    return render(request, 'users/questionnaire.html', {'questionnaire_form': questionnaire_form})


def signup(request):
    '''get:新規登録ページを表示　post:新規登録処理'''
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            input_email = form.cleaned_data['email']
            input_password = form.cleaned_data['password1']
            new_user = authenticate(
                email=input_email, password=input_password)
            if new_user is not None:
                login(request, new_user)
                return redirect('users:index')
        else:
            messages.warning(request, '無効な値が入力されました')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/signup.html', {'form': form})


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更後"""

    def get(self, request):
        messages.success(request, 'パスワードを変更しました')
        return render(request, 'users/login.html')


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'users/mail_template/password_reset/subject.txt'
    email_template_name = 'users/mail_template/password_reset/message.txt'
    template_name = 'users/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'users/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('users:password_reset_complete')
    template_name = 'users/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""

    def get(self, request):
        messages.success(request, 'パスワードを再設定しました')
        return render(request, 'users/login.html')


def get_address(zip_code):
    '''郵便番号から住所を取得'''
    REQUEST_URL = f'http://zipcloud.ibsnet.co.jp/api/search?zipcode={zip_code}'
    address = ''
    response = requests.get(REQUEST_URL, timeout=5)
    response = json.loads(response.text)
    result, api_status = response['results'], response['status']

app/portfolio/templates/users/friend_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-secondary">友人一覧</h2>
{% for friend in friends %}
<div class="card m-2 shadow-sm">
    <div class="card-body row p-2">
        <div class="col-3">
            <a href="{% url 'users:user_detail' friend.id %}">
                {% if friend.icon %}
                <img class="img-thumbnail rounded-circle img-md" src="{{ friend.icon.url }}" alt="">
                {% else %}
                <img class="img-thumbnail rounded-circle img-md" src="{% static 'default_icon.jpg' %}" alt="">
                {% endif %}
            </a>
        </div>
        <div class="col-9">
            <div class="row h-75">
                <div class="col-4">
                    <a class="h3" href="{% url 'users:user_detail' friend.id %}">
                        <h2>{{ friend.name }}</h2>
                    </a>
                </div>
                <div class="col-8">
                    <p><u>投稿数：{{ friend.article_set.count }}</u></p>
                    <p><u>出品数：{{ friend.product_set.count }}</u></p>
                </div>
            </div>
            {% if friend.message %}
            <div class="h-25">
                <p class="text-muted">{{ friend.message }}</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}

<nav>
    <ul class="pagination justify-content-center">
        {% if friends.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'users:friend_list' %}?page=1">&laquo;</a></li>
        <li class="page-item">
            <a class="page-link" href="{% url 'users:friend_list' %}?page={{ friends.previous_page_number }}">
                {{ friends.previous_page_number }}</a>
        </li>
        {% endif %}
        <li class="page-item active">
            <span class="page-link" href="#">{{ friends.number }}</span>
        </li>
        {% if friends.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'users:friend_list' %}?page={{ friends.next_page_number }}">
                {{ friends.next_page_number }}</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'users:friend_list' %}?page={{ friends.paginator.num_pages }}">
                &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

app/portfolio/templates/users/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/owl/owl.carousel.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/owl/owl.theme.default.css' %}">
{% endblock %}

{% block content %}

<div class="container-fluid px-3 mt-4 mb-5">
    <div class="container bg-danger rounded-lg">
        <a class="h2 text-light d-inline-block ml-3 my-1" href="{% url 'ecapp:index' %}?page=1">
            EC
        </a>
    </div>
    {% include 'ecapp/product_list.html' %}
</div>

<div class="container-fulid px-3 mb-5">
    <div class="container bg-info rounded-lg">
        <a class="h2 text-light d-inline-block ml-3 my-1" href="{% url 'snsapp:index' %}?page=1">
            SNS
        </a>
    </div>
    <div class="container pt-3 mb-5 border border-info rounded" id="article">
        {% include 'snsapp/article_list.html' %}
        <div class="text-center mb-2">
            <a href="{% url 'users:index' %}?articles={{ article_num }}">
                <button class="border border-0 bg-white"><i class="fas fa-angle-double-down fa-3x"
                        style="color: darkcyan;"></i></button></a>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript" src="https://kit.fontawesome.com/c25d00f6dc.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'js/display_eval.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/owl/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/my_owl.js' %}"></script>
<script type="text/javascript" src="{% static 'js/product.js' %}"></script>
<script type="text/javascript" src="{% static 'js/article.js' %}"></script>
{% endblock %}

app/portfolio/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card mt-10">
        <div class="card-body">
            <h4 class="card-title mb-4">ログイン</h4>

            <form method="POST" class="signin">{% csrf_token %}
                {% if form.errors %}
                <p class="text-danger">メールアドレスかパスワードが間違っています。</p>
                {% endif %}
                <div class="form-group">
                    <label>Eメール</label>
                    <input name="username" class="form-control" placeholder="ex.name@gmail.com" type="email">
                </div>
                <div class="form-group">
                    <a class="float-right" href="{% url 'users:password_reset' %}">パスワードを忘れた場合</a>
                    <label>パスワード</label>
                    <input name="password" class="form-control" placeholder="********" type="password">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block" value="ログイン">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/portfolio/templates/users/my_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fulid border rounded mb-3">
    <div class="container row">
        {% if request.user.icon %}
        <img class="col-2 img-thumbnail rounded-circle m-1" src="{{ request.user.icon.url }}" alt="">
        {% else %}
        <img class="col-2 img-thumbnail rounded-circle m-1" src="{% static 'default_icon.jpg' %}" alt="">
        {% endif %}
        <div class="col-9 ml-auto d-flex align-items-center">
            <p class="d-inline-block m-1 text-center">{{ request.user.message }}</p>
        </div>
    </div>
    <table class="table m-0">
        <tr>
            <th>アカウント名</th>
            <td>{{ request.user.name }}</td>
        </tr>
        <tr>
            <th>Eメールアドレス</th>
            <td>{{ request.user.email }}</td>
        </tr>
        <tr>
            <th>住所</th>
            <td>{{ request.user.address }}</td>
        </tr>
        <tr>
            <th>ポイント</th>
            <td>{{ request.user.point }}<span class="d-block ml-auto"><a class="text-muted small"
                        href="{% url 'users:questionnaire' %}">※アンケートに答えてポイントゲット</a></span>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{% url 'users:edit_profile' %}">アカウント情報を変更</a>
                    <a class="btn btn-secondary" href="{% url 'users:password_change' %}">パスワードを変更</a>
                </div>
            </td>
        </tr>
    </table>

</div>
<div class="container-fluid mb-3">
    <ul class="list-group">
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'snsapp:my_articles' %}?page=1">自身の記事</a>
        </li>
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'ecapp:my_products' %}?page=1">自身の出品</a>
        </li>
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'ecapp:fav_products' %}?page=1">お気に入り商品</a>
        </li>
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'ecapp:cart' 0 %}?page=1">カート</a>
        </li>
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'ecapp:order_history' %}?page=1">注文履歴</a>
        </li>
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'users:friend_list' %}?page=1">友人一覧</a>
        </li>
        <li class="list-group-item text-center">
            <a class="text-secondary" href="{% url 'users:point_history' %}?page=1">ポイント履歴</a>
        </li>
    </ul>
</div>

{% endblock %}

app/portfolio/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url 'users:login' %}" class="btn btn-primary btn-lg">ログイン</a>

{% endblock %}

app/portfolio/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block content %}

<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>

{% endblock %}

app/portfolio/templates/users/point_history.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

<h2 class="text-secondary">ポイント履歴</h2>
<div class="container my-4">
    <table class="table table-striped border">
        <tr>
            <th>日時</th>
            <th>イベント</th>
            <th>ポイント増減</th>
        </tr>
        {% for pf in point_fluctuations %}
        <tr>
            <td>{{ pf.created_at　| date:"Y/m/d" }}</td>
            <td>{{ pf.event }}</td>
            <td>{{ pf.change | intcomma }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

<nav>
    <ul class="pagination justify-content-center">
        {% if point_fluctuations.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'users:point_history' %}?page=1">&laquo;</a></li>
        <li class="page-item">
            <a class="page-link"
                href="{% url 'users:point_history' %}?page={{ point_fluctuations.previous_page_number }}">
                {{ point_fluctuations.previous_page_number }}</a>
        </li>
        {% endif %}
        <li class="page-item active">
            <span class="page-link" href="#">{{ point_fluctuations.number }}</span>
        </li>
        {% if point_fluctuations.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'users:point_history' %}?page={{ point_fluctuations.next_page_number }}">
                {{ point_fluctuations.next_page_number }}</a>
        </li>
        <li class="page-item">
            <a class="page-link"
                href="{% url 'users:point_history' %}?page={{ point_fluctuations.paginator.num_pages }}">
                &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>

<div class="float-right mr-4 mb-5">
    <h4><span class="small">現在: </span>{{ request.user.point | intcomma }}<span class="small">point</span></h4>
</div>

{% endblock %}

app/portfolio/templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/owl/owl.carousel.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/owl/owl.theme.default.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <div class="media mx-auto">
        <div class="">
            {% if user.icon %}
            <img class="img-thumbnail rounded-circle img-icon" src="{{ user.icon.url }}" alt="">
            {% else %}
            <img class="img-thumbnail rounded-circle img-icon" src="{% static 'default_icon.jpg' %}" alt="">
            {% endif %}
        </div>
        <div class="media-body py-3" style="height: 200px;">

            {% if is_friend %}
            <form class="float-right" action="{% url 'users:add_friend' user.id %}" method="post">{% csrf_token %}
                <input type="submit" name="add_friend" value="友達追加済み" class="btn btn-primary">
            </form>
            {% elif user != request.user %}
            <form class="float-right" action="{% url 'users:add_friend' user.id %}" method="post">{% csrf_token %}
                <input type="submit" name="add_friend" value="友達追加" class="btn btn-primary">
            </form>
            {% endif %}

            <h1 class="d-inline-block ml-2">{{ user.name }}</h1>
            <div class="my-2 text-center">
                {% if user.message %}
                <h4 class="text-muted">{{ user.message }}</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container-fluid px-3 mt-4 mb-5">
    <div class="container bg-danger rounded-lg">
        <a class="h2 text-light d-inline-block ml-3 my-1" href="{% url 'ecapp:index' %}?page=1">
            商品一覧
        </a>
    </div>
    {% include 'ecapp/product_list.html' %}
</div>

<div class="container-fulid px-3 mb-5">
    <div class="container bg-info rounded-lg">
        <a class="h2 text-light d-inline-block ml-3 my-1" href="{% url 'snsapp:index' %}?page=1">
            記事一覧
        </a>
    </div>
    <div class="container pt-3 mb-5 border border-info rounded" id="article">
        {% include 'snsapp/article_list.html' %}
        {% if articles %}
        <div class="text-center mb-2">
            <a href="{% url 'users:user_detail' user.id %}?articles={{ article_num }}">
                <button class="border border-0 bg-white"><i class="fas fa-angle-double-down fa-3x"
                        style="color: darkcyan;"></i></button></a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="https://kit.fontawesome.com/c25d00f6dc.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'js/display_eval.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/owl/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/my_owl.js' %}"></script>
<script type="text/javascript" src="{% static 'js/product.js' %}"></script>
<script type="text/javascript" src="{% static 'js/article.js' %}"></script>
{% endblock %}