app/portfolio/ecapp/urls.py
from django.urls import path
from . import views


app_name = 'ecapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('fav_products/', views.fav_products, name='fav_products'),
    path('my_products/', views.my_products, name='my_products'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('product/', views.detail_from_article, name='detail_from_article'),
    path('wheather_fav_new/', views.WheatherFavNew.as_view(),
         name='wheather_fav_new'),
    path('toggle_fav/', views.ToggleFav.as_view(), name='toggle_fav'),
    path('cart/<int:which_cart>/', views.cart, name='cart'),
    path('change_item_amount/<int:which_cart>/', views.change_item_amount,
         name='change_item_amount'),
    path('delete_cart_product/<int:which_cart>/<int:product_id>/',
         views.delete_cart_product, name='delete_cart_product'),
    path('order_history/', views.order_history, name='order_history'),
    path('sell/', views.sell, name='sell'),
    path('delete/<int:product_id>', views.delete, name='delete'),
]

app/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from ecapp import views as ec_views
from snsapp import views as sns_views


router = routers.DefaultRouter()
router.register('products', ec_views.ProductViewSet)
router.register('articles', sns_views.ArticleViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('ecapp/', include('ecapp.urls')),
    path('snsapp/', include('snsapp.urls')),
    path('api/', include(router.urls)),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/portfolio/snsapp/urls.py
from django.urls import path
from . import views

app_name = 'snsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('good_articles/', views.good_articles, name='good_articles'),
    path('my_articles/', views.my_articles, name='my_articles'),
    path('post_article/', views.post_article, name='post_article'),
    path('delete/<int:article_id>/', views.delete, name='delete'),
    path('change_good/', views.ChangeGood.as_view(), name='change_good'),
    path('gooded_articles/', views.GoodedArticles.as_view(), name='gooded_articles'),
]

app/portfolio/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import EmailAuthenticationForm

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('my_page/', views.my_page, name='my_page'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('friend_list/', views.friend_list, name='friend_list'),
    path('add_friend/<int:user_id>', views.add_friend, name='add_friend'),
    path('point_history/', views.point_history, name='point_history'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
]

app/portfolio/ecapp/models.py
from django.db import models


class Product(models.Model):
    """商品"""
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=1)
    image = models.ImageField(upload_to='product')
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Sale(models.Model):
    """売上情報"""
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    amount = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField("商品単価")
    created_at = models.DateTimeField(auto_now_add=True)

app/portfolio/ecapp/forms.py
from django import forms
from .models import Product


class AddToCartForm(forms.Form):
    def __init__(self, product_id, *args, **kwargs):
        super(AddToCartForm, self).__init__(*args, **kwargs)
        product = Product.objects.get(id=product_id)
        amount = product.amount
        self.fields['num'] = forms.IntegerField(
            label='数量',
            initial=1,
            min_value=1,
            max_value=amount,
            required=True,
        )


class SellForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'amount', 'image']

app/portfolio/ecapp/views.py
import re
import requests
import datetime
import collections

from django.conf import settings
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from rest_framework import viewsets
from rest_framework import permissions, authentication
from rest_framework.response import Response
from rest_framework.views import APIView

from users.models import Friend, PointFluctuation
from users.forms import SearchForm, ProfileForm
from users.views import get_address
from snsapp.models import Article
from .models import Product, Sale
from .forms import AddToCartForm, SellForm
from .serializers import ProductSerializer


def index(request):
    '''get:ecトップページを表示　post:検索結果で絞り込んでecトップページを表示'''
    search_form = SearchForm(request.POST or None)
    products = Product.objects.all().order_by('-created_at')
    # 検索フォーム
    if request.method == 'POST':
        if search_form.is_valid():
            user = request.user
            select = search_form.cleaned_data['select']
            keyword = search_form.cleaned_data['keyword']

            # ユーザー選択時の処理
            if select == '友人のみ':
                result_users = []
                if user.is_authenticated:
                    for friend_instance in Friend.objects.filter(owner=user):
                        friend = friend_instance.friends
                        result_users.append(friend)
            if select == '全体':
                user_model = get_user_model()
                result_users = user_model.objects.all()

            searched_products = []
            for result_user in result_users:
                products = Product.objects.filter(owner=result_user)
                for product in products:
                    searched_products.append(product)

            # ワード検索時の処理
            if keyword:
                products = []
                for product in searched_products:
                    name = product.name
                    owner = product.owner.name
                    description = product.description
                    if not description:
                        description = ''
                    text_list = [name, owner, description]
                    text = ' '.join(text_list)
                    if re.findall(keyword, text, re.IGNORECASE):
                        products.append(product)
                messages.success(request, f'"{keyword}"の検索結果（{select}）')
            if not keyword:
                products = searched_products
                messages.success(request, f'絞り込み（{select}）')
        else:
            messages.warning(request, '無効な検索です')
            return redirect('ecapp:index')

    num = request.GET.get('page')
    if not num:
        num = 1
    products = Paginator(products, 12)
    products = products.get_page(num)
    context = {
        'search_form': search_form,
        'products': products
    }
    return render(request, 'ecapp/index.html', context)


@login_required
def fav_products(request):
    '''お気に入り商品を絞り込んでecトップページを表示'''
    user = request.user
    products = user.fav_products.all().order_by('-created_at')
    num = request.GET.get('page')
    if not num:
        num = 1
    products = Paginator(products, 12)
    products = products.get_page(num)
    return render(request, 'ecapp/index.html', {'products': products})


@login_required
def my_products(request):
    '''自身の商品を絞り込んでecトップページを表示'''
    user = request.user
    products = Product.objects.filter(owner=user).order_by('-created_at')
    num = request.GET.get('page')
    if not num:
        num = 1
    products = Paginator(products, 12)
    products = products.get_page(num)
    return render(request, 'ecapp/index.html', {'products': products})


def detail(request, product_id):
    '''get:商品詳細ページを表示　post:商品をカートに入れ、カートページを表示
    {product_id:商品ID}'''
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        num = request.POST['num']
        num = int(num)
        if num == 0:
            messages.warning(request, '個数を選択してください')
            return redirect('ecapp:detail', product_id=product_id)
        # 今すぐ購入が押されたとき
        if 'buy_now' in request.POST:
            cart_products = {product: num}
            purchase_form = ProfileForm(request.POST, None)
            total_price = product.price * num
            request.session['instant_cart'] = {str(product_id): num}
            context = {
                'purchase_form': purchase_form,
                'cart_products': cart_products,
                'total_price': total_price,
                'which_cart': 1,
            }
            return render(request, 'ecapp/cart.html', context)
        # カートに入れるが押された時
        else:
            if 'cart' in request.session:
                if str(product_id) in request.session['cart']:
                    request.session['cart'][str(product_id)] += num
                else:
                    request.session['cart'][str(product_id)] = num
            else:
                request.session['cart'] = {str(product_id): num}
            messages.success(request, f"{product.name}を{num}個カートに入れました！")
            # カートへが押された時
            if 'to_cart' in request.POST:
                return redirect('ecapp:cart', which_cart=0)
            # 買い物を続けるが押された時
            elif 'go_on' in request.POST:
                return redirect('ecapp:index')
            # リコメンド商品が押された時
            elif 'product' in request.POST:
                next_product_id = request.POST['product']
                return redirect('ecapp:detail', product_id=next_product_id)
    else:
        # 商品の評価記事と平均評価、評価数を取り出す
        articles = product.article_set.all().order_by('-created_at')
        if articles:
            total = 0
            for article in articles:
                total += article.evaluation
            review_num = len(articles)
            mean = total / review_num
            mean_eval = round(mean)
        else:
            mean_eval = 0
            review_num = 0
        # 表示する記事数の処理
        # param {articles:現在表示している記事数}
        article_num = request.GET.get('articles')
        if not article_num:
            article_num = 0
        article_num = int(article_num)
        if article_num == len(articles) and article_num != 0:
            messages.warning(request, '既に全ての記事を表示しています')
        else:
            article_num += 10
            articles = articles[:article_num]
        # リコメンドする商品
        # 同商品を買ったユーザーが買った別商品（多い順に３つ、同数の時は購入日付が近いもの）
        rel_products = []
        self_sales = Sale.objects.filter(
            product=product).order_by('-created_at')
        for self_sale in self_sales:
            user = self_sale.user
            sales = Sale.objects.filter(user=user)
            for sale in sales:
                recommend_product = sale.product
                if recommend_product.id == product_id:
                    continue
                rel_products.append(recommend_product)
        recommend_products = []
        recommend_products_col = collections.Counter(
            rel_products).most_common(3)
        for recommend_product in recommend_products_col:
            recommend_products.append(recommend_product[0])

        add_to_cart_form = AddToCartForm(product_id=product_id)
        context = {
            'product': product,
            'articles': articles,
            'evaluation': mean_eval,
            'review_num': review_num,
            'article_num': article_num,
            'recommend_products': recommend_products,
            'add_to_cart_form': add_to_cart_form,
            'next': 'product',
        }
    return render(request, 'ecapp/detail.html', context)


def detail_from_article(request):
    '''商品の評価記事から商品詳細ページに飛んだ場合、セッションに商品IDと記事IDを記録'''
    product_id = request.GET.get('product_id')
    article_id = request.GET.get('article_id')
    if 'product_from_article' in request.session:
        request.session['product_from_article'][str(
            product_id)] = str(article_id)
    else:
        request.session['product_from_article'] = {
            str(product_id): str(article_id)}
    product_id = int(product_id)
    return detail(request, product_id)


class WheatherFavNew(APIView):
    '''お気に入り商品と一週間以内に出品された商品のIDを返す'''

    def get(self, request):
        fav_ids = []
        new_ids = []
        if request.user.is_authenticated:
            user = request.user
            fav_products = user.fav_products.all()
            for product in fav_products:
                fav_ids.append(product.id)

        for product in Product.objects.all():
            old = product.created_at + datetime.timedelta(days=7)
            if datetime.datetime.today().astimezone() < old:
                new_ids.append(product.id)

        data = {
            'fav_ids': fav_ids,
            'new_ids': new_ids,
        }
        return JsonResponse(data, safe=False)


class ToggleFav(APIView):
    '''商品のお気に入り状態を切り替える'''
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        user = request.user
        pk = request.GET.get('pk')
        product = get_object_or_404(Product, pk=pk)
        # 既にgoodを押していた場合
        if product in user.fav_products.all():
            user.fav_products.remove(product)
        # 新しくgoodを押した場合
        else:
            user.fav_products.add(product)
        return Response(None)


@login_required
def cart(request, which_cart):

app/portfolio/templates/ecapp/cart.html
{% extends 'base.html' %}
{% load humanize %}
{% load filters %}

{% block content %}

<div class="alert alert-danger">
    {% if which_cart == 0 %}
    <h3>カート</h3>
    {% else %}
    <h3>カート外から購入</h3>
    {% endif %}
</div>

<div class="row">
    <aside class="col-lg-9">
        <div class="card">
            <div class="table-responsive">
                <table class="table table-borderless table-shopping-cart">
                    <thead class="text-muted">
                        <tr class="small text-uppercase">
                            <th scope="col">Product</th>
                            <th scope="col" width="120">Quantity</th>
                            <th scope="col" width="120">Price</th>
                            <th scope="col" class="text-right d-none d-md-block" width="200"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product, num in cart_products.items %}
                        <tr>
                            <td>
                                <figure class="itemside align-items-center ">
                                    <div class="aside">
                                        <img class="img-md img-fluid" src="{{ product.image.url }}" alt="">
                                        <div class="d-inline-block">
                                            <a href="{% url 'ecapp:detail' product.id %}"
                                                class="title text-dark h4">{{ product.name }}</a>
                                            <p class="text-muted small">在庫: {{ product.amount }}</p>
                                            <p class="text-muted small">出品者: <a
                                                    href="{% url 'users:user_detail' product.owner.id %}">{{ product.owner.name }}</a>
                                            </p>
                                        </div>
                                    </div>
                                </figure>
                            </td>
                            <td>
                                <form action="{% url 'ecapp:change_item_amount' which_cart %}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <input type="hidden" name="product_id" value="{{ product.id }}">
                                        <input type="submit" name="action_remove" value="-"
                                            class="btn btn-light input-size">
                                        <input type="text" readonly='' value="{{ num | intcomma }}" class="input-size">
                                        <input type="submit" name="action_add" value="+"
                                            class="btn btn-light input-size">
                                    </div>
                                </form>
                            </td>
                            <td>
                                <div class="price-wrap">
                                    <var class="price">{{ product.price | multiply:num | intcomma }}</var>point
                                    <var
                                        class="d-block price text-muted small">単価{{ product.price | intcomma }}point</var>
                                </div>
                            </td>
                            <td class="text-right d-none d-md-block">
                                <form action="{% url 'ecapp:delete_cart_product' which_cart product.id %}"
                                    method="POST">
                                    {% csrf_token %}
                                    <input type="submit" value="削除" class="btn btn-danger">
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </aside>
    <aside class="col-lg-3">
        <div class="card">
            <div class="card-body pb-0">
                <form action="{% url 'ecapp:cart' which_cart %}" method="post">{% csrf_token %}
                    {% if request.user.address %}
                    <p><strong class="text-muted">{{ request.user.address }}</strong> にお届け</p>
                    {% else %}
                    <p class="text-muted">住所が設定されていません</p>
                    <div class="purchase-form-address">
                        <div>
                            {{ purchase_form.non_field_errors }}
                            {{ purchase_form.zip_code.label_tag }}
                            {{ purchase_form.zip_code }}
                            <input class="btn btn-primary my-1" type="submit" name="search_address" value="住所を検索">
                            <span>{{ purchase_form.zip_code.help_text }}</span>
                        </div>
                        <div>
                            {{ purchase_form.address.label_tag }}
                            {{ purchase_form.address }}
                        </div>
                    </div>
                    {% endif %}
                    <dl class="dlist-align">
                        <dt class="d-inline-block">請求額：</dt>
                        <dd class="text-right text-dark d-inline-block h4">
                            <strong>{{ total_price | intcomma }}point</strong>
                        </dd>
                        <input type="submit" name="buy_product" value="購入する"
                            class="btn btn-primary d-block mx-auto mt-3 mb-0">
                    </dl>
                </form>
            </div>
        </div>
    </aside>
</div>

{% endblock %}

app/portfolio/templates/ecapp/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<div class="card" id="product">
    <div class="row no-gutters">
        <aside class="col-md-6 d-flex align-items-center">
            <img class="img-lg d-block mx-auto" src="{{ product.image.url }}" alt="">
        </aside>
        <main class="col-md-6 border-left p-2">
            {% if product.owner == request.user %}
            <form action="{% url 'ecapp:delete' product.id %}" method="post" class="float-right">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit" onclick="return confirm('本当に削除しますか？');">削除</button>
            </form>
            {% endif %}
            <product-good ref="{{ product.id }}" data-id="{{ product.id }}"
                data-authenticated="{{ request.user.is_authenticated }}"></product-good>

            <article class="content-body">
                <h1 class="">{{ product.name }}</h1>
                <ul style="list-style: none;" class="pl-0 my-2 d-inline-block">
                    <li class="d-inline-block">
                        <star-icon :eval="eval" data-id="1" data-eval="{{ evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="2" data-eval="{{ evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="3" data-eval="{{ evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="4" data-eval="{{ evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="5" data-eval="{{ evaluation }}"></star-icon>
                    </li>
                </ul>
                <span class="small text-muted">(評価数: <strong>{{review_num}}</strong>)</span>
                <div class="mb-3">
                    <h4><var>{{ product.price | intcomma }}</var>point</h4>
                </div>
                <p>{{ product.description }}</p>
                <p class="text-muted d-inline-block mb-0">在庫：　{{ product.amount }}個</p>
                <span class="float-right mr-2">出品者：<a
                        href="{% url 'users:user_detail' product.owner.id %}">{{ product.owner.name }}</a>
                </span>
                <hr>
                {% if request.user.is_authenticated %}
                <form action="{% url 'ecapp:detail' product.id %}" method="post">{% csrf_token %}
                    {{ add_to_cart_form.as_p }}
                    <button type="submit" name="buy_now" class="btn btn-primary">今すぐ購入</button>
                    <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#cart">
                        <span class="text">カートに入れる</span>
                        <i class="fas fa-shopping-cart"></i>
                    </button>
                    <div class="modal fade" id="cart">
                        <div class="modal-dialog modal-dialog-centered modal-lg">
                            <div class="modal-content">
                                <div class="modal-header bg-info">
                                    <h5 class="modal-title text-light">この商品をご購入された方はこちらの商品もよくご購入されています</h5>
                                    <button type="button" class="close" data-dismiss="modal">
                                        <span>&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% if recommend_products %}
                                    <div class="row mx-2">
                                        {% for recommend_product in recommend_products %}
                                        <figure class="card card-product-grid shadow-sm col-md-3">
                                            <button type="submit" name="product" value="{{ recommend_product.id }}"
                                                class="btn btn-link">
                                                <div class="img-wrap">
                                                    <a href="{% url 'ecapp:detail' recommend_product.id %}">
                                                        <img src="{{ recommend_product.image.url }}"
                                                            class="img-fluid img-lg"></a>
                                                </div>
                                                <figcaption class="info-wrap text-center border-top">
                                                    <a href="{% url 'ecapp:detail' recommend_product.id %}"
                                                        class="title text-truncate d-block">{{ recommend_product.name }}</a>
                                                    <small class="text-muted">在庫: {{ recommend_product.amount }}</small>
                                                    <div class="price mt-2">
                                                        <strong>{{ recommend_product.price | intcomma }}</strong>point
                                                    </div>
                                                </figcaption>
                                            </button>
                                        </figure>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    <p>この商品の購入履歴はありません</p>
                                    {% endif %}
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" name="go_on" class="btn btn-outline-primary">買い物を続ける</button>
                                    <button type="submit" name="to_cart" class="btn btn-primary">
                                        <span class="text">カートへ</span>
                                        <i class="fas fa-shopping-cart"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                {% else %}
                <a href="{% url 'users:login' %}?next={{ request.path }}">
                    <button class="btn btn-primary">ログインして購入する</button>
                </a>
                {% endif %}
            </article>
        </main>
    </div>
</div>

<div class="container-fulid px-3 mb-5 mt-3">
    <div class="container bg-info rounded-lg">
        <h2 class="text-light d-inline-block ml-3 my-1">
            {{ product.name }}<small>に関する記事</small>
        </h2>
    </div>
    <div class="container pt-3 border border-info rounded" id=article>
        {% if not articles %}
        <h5 class="text-center font-weight-bold text-muted mb-4 mt-1">未投稿</h5>
        {% else %}
        {% for article in articles %}
        <div class="media row mb-3 border-bottom border-info p-3 shadow-sm">
            <div class="col-2"></div>
            <div class="media-body col-10">
                {% if article.author == request.user %}
                <form action="{% url 'snsapp:delete' article.id %}" method="post" class="float-right ml-3">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input class="btn btn-outline-danger" type="submit" next="{{ next }}"
                        onclick="return confirm('本当に削除しますか？');" value="削除">
                </form>
                {% endif %}
                <p>{{ article.content }}</p>
                <ul style="list-style: none;" class="pl-0">
                    <li class="d-inline-block">
                        <star-icon :eval="eval" data-id="1" data-eval="{{ article.evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="2" data-eval="{{ article.evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="3" data-eval="{{ article.evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="4" data-eval="{{ article.evaluation }}"></star-icon>
                        <star-icon :eval="eval" data-id="5" data-eval="{{ article.evaluation }}"></star-icon>
                    </li>
                </ul>
                <div class="mt-auto float-right">
                    <div class="d-flex align-items-end">
                        <span class="font-italic mr-2">{{ article.created_at | date:"Y/m/d f" }}</span>
                        by<a href="{% url 'users:user_detail' article.author.id %}">{{ article.author.name }}</a>
                    </div>
                </div>
            </div>
            <article-good id="good" ref="{{ article.id }}" data-id="{{ article.id }}"
                data-count="{{ article.good_count }}" data-authenticated="{{ request.user.is_authenticated }}">
            </article-good>
        </div>
        {% endfor %}
        <div class="text-center mb-2">
            <a href="{% url 'ecapp:detail' product.id %}?articles={{ article_num }}">
                <button class="border border-0 bg-white"><i class="fas fa-angle-double-down fa-3x"
                        style="color: darkcyan;"></i></button></a>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript" src="https://kit.fontawesome.com/c25d00f6dc.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'js/display_eval.js' %}"></script>
<script type="text/javascript" src="{% static 'js/product.js' %}"></script>
<script type="text/javascript" src="{% static 'js/article.js' %}"></script>
{% endblock %}